### ISSUE TITLE
Rename mash-related stuff

### ISSUE THREAD

**Issue by ya55en** [ya55en/sh-stdlib#1]
The current code contains mash-related stuff like `MASH_IMPORT_PATH`.

We want all these renamed in a way that removes any dependencies or references to mash-specific terms.

Examples:
- `MASH_IMPORT_PATH` becomes `POSIXSH_IMPORT_PATH`
- `MASH_HOME` becomes `POSIXSH_STDLIB_HOME`

**Comment by veren-damyanov** [comment]
Merged to main. Closing.
